[package]
name = "diesel_timestamp_error"
version = "0.1.0"
authors = ["Nicola Musatti <nicola.musatti@gmail.com>"]

[dependencies]
chrono = "0.4.0"
diesel = { version = "0.13.0", features = [ "chrono", "sqlite" ] }
diesel_codegen = { version = "0.13.0", features = [ "sqlite" ] }
dotenv = "0.9.0"
